apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
  - name: web
    image: alexinnru/otus_k8s:centos_nginx
    volumeMounts:
    - mountPath: /app
      name: app      
  - name: init-web
    image: busybox:1.31.0
    volumeMounts:
    - mountPath: /app
      name: app      
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
  volumes:
  - name: app
    emptyDir: {}